"""Thin durable runtime kernel (design §10.2).

This package adds task coordination, recovery facts, fencing, and reliable
delivery around the existing Agent Core. It does not replace Agent Core.

Public surface:

- :class:`RuntimeConfig` — parsed and validated runtime configuration.
- :class:`SqliteRuntimeStore` — the only production Runtime Store façade.
- Narrow view Protocols in :mod:`miniunicorn.runtime.contracts`.

Importing this package does not import SQLite; SQLite is imported lazily
by :mod:`miniunicorn.runtime.sqlite` so Agent unit tests can run without
the runtime implementation (design §6.17).
"""

from __future__ import annotations

from miniunicorn.runtime.config import RuntimeConfig, RuntimeMode, parse_runtime_config
from miniunicorn.runtime.contracts import (
    ClaimRequest,
    ClaimedTask,
    ClaimResult,
    CompletionResult,
    ControlResult,
    DeliveryLedger,
    ExecutionJournal,
    InboundTaskEnvelope,
    InternalTaskEnvelope,
    MaintenanceLedger,
    OutboxClaim,
    ReclaimResult,
    ResourceLedger,
    ResourceLease,
    ResourceLeaseRequest,
    RetryDecision,
    RuntimeStore,
    SessionCommitLedger,
    SubmitResult,
    TaskClaim,
    TaskControlRequest,
    TaskHandle,
    TaskIngressStore,
    TaskRecord,
    TaskSnapshot,
    WaitResult,
    WorkerLedger,
)
from miniunicorn.runtime.models import (
    BLOB_ENCODING,
    BLOB_KIND,
    DELIVERY_RECOVERY,
    EVENT_TYPES,
    OUTBOX_DEDUP_KINDS,
    TASK_KINDS,
    CONTROL_KINDS,
    TASK_STATES,
    TERMINAL_TASK_STATES,
    TRANSITIONS,
    BlobRecord,
    BlobWrite,
    CheckpointWrite,
    CompletionWrite,
    ControlOutcomeWrite,
    DeliveryReceipt,
    DeliveryResolution,
    DurableEventRecord,
    InternalCompletionWrite,
    MediaRef,
    ModelAttemptWrite,
    ModelResultWrite,
    OutboxRecord,
    PreparedToolWrite,
    RequestScope,
    ResourceLeaseRecord,
    RetentionBatch,
    RetentionPolicy,
    RetentionResult,
    RetryKind,
    SessionCommitRecord,
    SessionCommitWrite,
    TaskControlRecord,
    TaskEventRecord,
    TaskFailure,
    ToolAttemptRecord,
    ToolAttemptWrite,
    ToolCallRecord,
    ToolResultWrite,
    WaitDecision,
    is_allowed_transition,
    is_terminal_state,
)

__all__ = [
    "RuntimeConfig",
    "RuntimeMode",
    "parse_runtime_config",
    # Contracts
    "ClaimRequest",
    "ClaimedTask",
    "ClaimResult",
    "CompletionResult",
    "ControlResult",
    "DeliveryLedger",
    "ExecutionJournal",
    "InboundTaskEnvelope",
    "InternalTaskEnvelope",
    "MaintenanceLedger",
    "OutboxClaim",
    "ReclaimResult",
    "ResourceLedger",
    "ResourceLease",
    "ResourceLeaseRequest",
    "RetryDecision",
    "RuntimeStore",
    "SessionCommitLedger",
    "SubmitResult",
    "TaskClaim",
    "TaskControlRequest",
    "TaskHandle",
    "TaskIngressStore",
    "TaskRecord",
    "TaskSnapshot",
    "WaitResult",
    "WorkerLedger",
    # Models
    "BLOB_ENCODING",
    "BLOB_KIND",
    "DELIVERY_RECOVERY",
    "EVENT_TYPES",
    "OUTBOX_DEDUP_KINDS",
    "TASK_KINDS",
    "CONTROL_KINDS",
    "TASK_STATES",
    "TERMINAL_TASK_STATES",
    "TRANSITIONS",
    "BlobRecord",
    "BlobWrite",
    "CheckpointWrite",
    "CompletionWrite",
    "ControlOutcomeWrite",
    "DeliveryReceipt",
    "DeliveryResolution",
    "DurableEventRecord",
    "InternalCompletionWrite",
    "MediaRef",
    "ModelAttemptWrite",
    "ModelResultWrite",
    "OutboxRecord",
    "PreparedToolWrite",
    "RequestScope",
    "ResourceLeaseRecord",
    "RetentionBatch",
    "RetentionPolicy",
    "RetentionResult",
    "RetryKind",
    "SessionCommitRecord",
    "SessionCommitWrite",
    "TaskControlRecord",
    "TaskEventRecord",
    "TaskFailure",
    "ToolAttemptRecord",
    "ToolAttemptWrite",
    "ToolCallRecord",
    "ToolResultWrite",
    "WaitDecision",
    "is_allowed_transition",
    "is_terminal_state",
]
